# Generated by Django 5.0.1 on 2024-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', upload_to='burguer/img'),
        ),
    ]
